export const previouslyUsedTech = [
  'BitBucket',
  'Circle CI',
  'Azure DevOps',
  'Microsoft SQL Server',
  'Microsoft Internet Information Services (IIS)',
  'PHP',
  'Delphi',
  'C++',
  'Python',
  'React',
  'angularjs (Version 1)',
  'Vue.js',
  'pagerduty',
  'logz.io',
  'jQuery',
  'ASP.NET',
  'Webpack',
  'Grunt',
  'Virtual Box',
  'VMWare',
  'Jira / Confluence',
  'Visual Studio Online / Azure / Team Foundation Server',
  'Protractor',
  'Cypress',
  'Apache HTTP Server',
  'IntelliJ',
  'Visual Studio',
  'Microsoft Test Manager',
  'Microsoft Virtual Machine Manager',
  'Crystal Reports',
  'Oracle Databases'
];
