export const recentlyUsedTech = [
  'Amazon Web Services',
  'Java',
  'C#',
  'TypeScript / JavaScript',
  'Docker / Docker Compose',
  'Angular',
  'Node.js',
  '.NET (Core)',
  'Vite',
  'HTML & CSS (incl. Sass, Scss, Less)',
  'Sentry',
  'nginx',
  'MySQL / MariaDB',
  'PostgreSQL',
  'Ubuntu',
  'Windows',
  'Hyper-V',
  'UTM',
  'macOS',
  'Windows Subsystem for Linux',
  'Cordova / Capacitor',
  'Electron',
  'Android SDK',
  'iOS',
  'express.js',
  'Spring Boot',
  'Swagger / OpenAPI',
  'GitHub',
  'GitHub Actions',
  'GitHub Packages',
  'GitLab',
  'Yarn / NPM',
  'NuGet',
  'Ansible',
  'Yeoman',
  'Godot',
  'Blender',
  'Terraform',
  'Visual Studio Code'
];