on: push

permissions:
  contents: write
  pages: write

name: Build & Deploy
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: yarn global add @codewyre/skwid
      - run: |
          cd application
          yarn build
          yarn prepare-deployment
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./application/dist